# project name
PROJECT_NAME: "lvi_sam"

lvi_sam:

  # Topics
  pointCloudTopic: "/os1_cloud_node1/points"               # Point cloud data
  imuTopic: "/imu/imu_mod"                         # IMU data
#  imuTopic: "/imu/imu"                         # IMU data

  save_path: true    #to /tmp/path.txt

  # Cloud normal computation
  computeTable: false    #range image lookup table
  loadRingTableDirectory: "/config/viral"
  loadSubmapTableDirectory: "/config/viral"

  # Heading
  useImuHeadingInitialization: true          # if using GPS data, set to "true"
  
  # Export settings
  savePCD: false                              # https://github.com/TixiaoShan/LIO-SAM/issues/3
  savePCDDirectory: "/Downloads/LOAM/"        # in your home folder, starts and ends with "/". Warning: the code deletes "LOAM" folder then recreates it. See "mapOptimization" for implementation

  # Extract plane in submap
  extractPlanes: true
  # check visibility and normal direction in point-to-plane association
  #  checkNormal: false
  checkNormal: true

  # ikd-tree local map
  local_map_length: 150.0                   # size of local map , local_map_length * local_map_length
  threshold_to_map_edge: 50.0               # lidar to map edge less than the distance, local map will be move

  # Sensor Settings
  Lidar_type: 2                                 # 1:Velodyne, 2: ouster
  N_SCAN: 16                                  # number of lidar channel (i.e., 16, 32, 64, 128)
  Horizon_SCAN: 1024                          # lidar horizontal resolution (Velodyne:1800, Ouster:512,1024,2048)
  timeField: "t"                           # point timestamp field, Velodyne - "time", Ouster - "t"
  downsampleRate: 1                           # default: 1. Downsample your data if too many points. i.e., 16 = 64 / 4, 16 = 16 / 1 

  # IMU Settings
  imuAccNoise: 6.0e-2
  imuGyrNoise: 5.0e-3
  imuAccBiasN: 8.0e-5
  imuGyrBiasN: 3.0e-6
  imuGravity: 9.80511
  imu_freq: 385                             # IMU rate
  
  # Extrinsics (lidar -> IMU), lidar系下，imu的位姿
  extrinsicTrans: [0.05, 0.0, -0.055]                # t  LiDAR <-- IMU
  extrinsicRot: [1, 0, 0,
                 0, 1, 0,
                 0, 0, 1]    # R  LiDAR <-- IMU
  extrinsicRPY: [1, 0, 0,
                 0, -1, 0,
                 0, 0, -1]     # R  IMU <-- LiDAR

  R_W2NED:      [ 1,  0,  0,
                  0, -1,  0,
                  0,  0, -1]

  # LOAM feature threshold
  edgeThreshold: 1.0
  surfThreshold: 0.1
  edgeFeatureMinValidNum: 10
  surfFeatureMinValidNum: 100

  # voxel filter params
  odometrySurfLeafSize: 0.4                     # default: 0.4
  mappingCornerLeafSize: 0.2                    # default: 0.2
  mappingSurfLeafSize: 0.4                      # default: 0.4
  OMPMapPoints: 100000                          # parallel voxel grid, default:100000
  #  OMPMapPoints: 99999999                          # parallel voxel grid, default:100000

  # robot motion constraint (in case you are using a 2D robot)
  z_tollerance: 1000        # meters
  rotation_tollerance: 1000 # radians

  # CPU Params
  numberOfCores: 4                              # number of cores for mapping optimization
  mappingProcessInterval: 0.15                  # seconds, regulate mapping frequency

  # Surrounding map
  surroundingkeyframeAddingDistThreshold: 1.0   # meters, regulate keyframe adding threshold
  surroundingkeyframeAddingAngleThreshold: 0.2  # radians, regulate keyframe adding threshold
  surroundingKeyframeDensity: 2.0               # meters, downsample surrounding keyframe poses   
  surroundingKeyframeSearchRadius: 50.0         # meters, within n meters scan-to-map optimization (when loop closure disabled)

  # Loop closure
  loopClosureEnableFlag: false
  surroundingKeyframeSize: 25                   # submap size (when loop closure enabled)
  historyKeyframeSearchRadius: 20.0             # meters, key frame that is within n meters from current pose will be considerd for loop closure
  historyKeyframeSearchTimeDiff: 30.0           # seconds, key frame that is n seconds older will be considered for loop closure
  historyKeyframeSearchNum: 25                  # number of hostory key frames will be fused into a submap for loop closure
  historyKeyframeFitnessScore: 0.3              # icp threshold, the smaller the better alignment

  # Visualization
  globalMapVisualizationSearchRadius: 1000.0    # meters, global map visualization radius
  globalMapVisualizationPoseDensity: 10.0       # meters, global map visualization keyframe density
  globalMapVisualizationLeafSize: 1.0           # meters, global map visualization cloud density